### ISSUE TITLE
Ensure user image is pulled as part of fig up

### ISSUE THREAD

**Issue by rgbkrk** [cloudpipe/cloudpipe#37]
On a fresh deployment if the user image isn't available, `fig up`/`cloudpipe` will fail.

**Comment by rgbkrk** [comment]
```
cloudpipe_1 | time="2015-01-01T20:35:53Z" level="info" msg="Initializing with loaded settings." admin account="admin" logging level="debug" mongo URL="mongo" port=8000
cloudpipe_1 | time="2015-01-01T20:36:05Z" level="fatal" msg="Unable to load application context." error="no reachable servers"
cloudpipe_cloudpipe_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
```

**Comment by rgbkrk** [comment]
For fun I tried letting the user image come up as part of the `fig.yml`:

```yaml
---
cloudpipe:
  build: .
  links:
  - mongo
  environment:
    PIPE_ADMINNAME: admin
    PIPE_ADMINKEY: 12345
    PIPE_LOGLEVEL: debug
  ports:
  - "8000:8000"
  volumes:
  - "/var/run/docker.sock:/var/run/docker.sock"
mongo:
  image: mongo:2.8
user:
  image: cloudpipe/runner-py2
```

That failed as awesomely as one would expect.

```
user_1      | Traceback (most recent call last):
user_1      |   File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
user_1      |     "__main__", fname, loader, pkg_name)
user_1      |   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
user_1      |     exec code in run_globals
user_1      |   File "/srv/runner/multyvacinit/pybootstrap.py", line 10, in <module>
user_1      |     (f, args, kwargs) = pickle.load(sys.stdin)
user_1      |   File "/usr/lib/python2.7/pickle.py", line 1378, in load
user_1      |     return Unpickler(file).load()
user_1      |   File "/usr/lib/python2.7/pickle.py", line 858, in load
user_1      |     dispatch[key](self)
user_1      |   File "/usr/lib/python2.7/pickle.py", line 880, in load_eof
user_1      |     raise EOFError
user_1      | EOFError
cloudpipe_user_1 exited with code 1
```

Either we:

* just document it in the readme
* bring it in as part of launching `cloudpipe/cloudpipe`
* provide a dummy `command` to the user image in fig.yml
